# Generated by Django 6.1.1 on 2026-09-22 13:39

from django.db import migrations
from marks.models import Profile as NewProfile


def fill_profiles_for_user(apps, schema_editor):
    Profile = apps.get_model("marks", "Profile")
    User = apps.get_model("auth", "User")
  
    for user in User.objects.all():
        if not hasattr(user, 'profile'):
            Profile.objects.create(user=user, role=NewProfile.Role.undefined)


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0003_alter_discipline_image_profile'),
    ]

    operations = [
        migrations.RunPython(fill_profiles_for_user, reverse_code=None)
    ]
